# Generated by Django 3.1.4 on 2020-12-04 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190218_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 8, 7, 30, 811560, tzinfo=utc)),
        ),
    ]
